### ISSUE TITLE
✨유저 로그인, 회원가입 기능 개발 

### ISSUE THREAD

**Issue by youhyeoneee** [hit-it-PDA/BE#1]
## 📌 Description
- 유저 로그인, 회원가입 기능을 개발합니다.

## 📝 To-do
- [x] API 개발 
   - [x] 이메일 회원가입
   - [x] 이메일 로그인
   - [x] 카카오 로그인 
- [x] 공통 리스폰스 적용 
   - [x] 이메일 회원가입
   - [x] 이메일 로그인
   - [x] 카카오 로그인 
- [x] 유효성 검사
   - [x] 어노테이션 이용 
   - [ ] 비밀번호 형식 있다면 추가
   - [ ] 조건별 주민등록번호 유효성 검사 메소드 추가하기 (ex. 90년대: 1-2, 00년대: 4-5 / 월별 일자)
- [x] 예외처리 
- [x] 이메일 회원가입 - JWT 적용, Security 적용 

### 추가 수정 사항
- [x] #19
- [x] #20
- [x] #22

**Comment by youhyeoneee** [comment]
### 나중에 할 일들 
- [x] 비밀번호 형식 있다면 유효성 검사 추가
- [x] 조건별 주민등록번호 유효성 검사 메소드 추가하기 (ex. 90년대: 1-2, 00년대: 4-5 / 월별 일자)
- [ ] 회원가입 시 중복된 전화번호 가진 유저 있는지 체크 
- [ ] 카카오 회원가입 - Security 적용
