### ISSUE TITLE
✨자체 서비스 포트폴리오 상세 펀드 조회 기능 개발

### ISSUE THREAD

**Issue by SEO-YJ** [hit-it-PDA/BE#29]
## 📌 Description
- 자체 서비스 포트폴리오 상세 펀드 조회 기능 개발

## 📝 To-do
  - [x] #17 에서 자체 서비스 포트폴리오의 ```id```를 전달했으므로, 해당 id를 url 에 담아서 포트폴리오 선택하도록 FE 측에 설명
  - [x] 자체 서비스 포트폴리오 상세 펀드 조회를 담당하는 파일 생성
    - [x]  PortfolioController에서는 PortfolioService로 부터 포트폴리오의 id 전달
    - [x]  PortfolioService는 해당 id를 where 절을 통해 Spring Data Jpa로 private_portfolios_fund_products 테이블에서 id => portfolio_id에 해당하는 모든 데이터 가져옴
    - [x] DB로 부터 데이터를 가져오기 위한 PortfolioFund Entity 생성
  - [x] DB로 부터 가져온 데이터를 전달하기 위한 HititPortfoliosFundsResponseDto 생성
