### ISSUE TITLE
✨포트폴리오 수익률 연산 기능 개발

### ISSUE THREAD

**Issue by SEO-YJ** [hit-it-PDA/BE#33]
## 📌 Description
- 포트폴리오 수익률 연산 기능 개발

## 📝 To-do
- [x] DataBase 수정
  - [x] private_portfolios_fund_products 테이블에 return_3m 데이터 모두 추가
- [x] 포트폴리오 수익률 연산 기능
  - [x] PortfolioService의 getHititPortfolios 메서드에 수익률 연산 로직 추가
  - [x] HititPortfoliosResponseDto에 return_3m 컬럼에 대응할 return3m 필드 추가
 - [x] 포트폴리오 상세 펀드 FE로 반환시 ```weight``` 값으로 오름차순 정렬하여 반환
 - [x] 포트폴리오 상세 펀드 FE로 반환시 weight 값으로 오름차순 시 동일한 비중일 경우 ```fundName``` 값으로 문자열 정렬 후 반환
 - [x] HititPortfoliosFundsResponseDto 필드명 snake_case -> camelCase로 수정
