### ISSUE TITLE
✨자체 서비스 포트폴리오 내 펀드 상세 조회

### ISSUE THREAD

**Issue by SEO-YJ** [hit-it-PDA/BE#35]
## 📌 Description
- 자체 서비스 포트폴리오 내 펀드 상세 조회

## 📝 To-do
- [x] 자체 서비스 포트폴리오 내 펀드 상세 조회 로직
  - [x] private_portfolios_fund_products 테이블에서 portfolio_id에 해당하는 데이터 가져오기
  - [x] fundId 에러 처리
  - [x] FE에서 유저가 선택한 fund 데이터 인덱스로 가져오기
  - [x] 선택한 fund의 fund_code로 private_portfolios_fund_assets에서 fund_code에 해당하는 데이터 가져오기
  - [x] 선택한 fund의 fund_code로 private_portfolios_fund_stocks에서 fund_code에 해당하는 데이터 가져오고 List<HititPortfoliosFundsStocksAndBondsResponseDto.FundStockDto> 형식으로 리스트로 저장
  - [x] 선택한 fund의 fund_code로 private_portfolios_fund_bonds에서 fund_code에 해당하는 데이터 가져오고 List<HititPortfoliosFundsStocksAndBondsResponseDto.FundBondDto> 형식으로 리스트로 저장

- [x] Repository 생성
  - [x] private_portfolios_fund_assets 테이블과 통신할 PortfolioFundAssetRepository 생성
  - [x] private_portfolios_fund_stocks 테이블과 통신할 PortfolioFundStockRepository 생성
  - [x] private_portfolios_fund_bonds 테이블과 통신할 PortfolioFundBondRepository 생성
- [x] Entity 생성
  - [x] private_portfolios_fund_assets 테이블과 통신할 PortfolioFundAsset Entity 생성
  - [x] private_portfolios_fund_stocks 테이블과 통신할 PortfolioFundStock Entity 생성
    - [x] PortfolioFundStock Entity의 복합키를 위한 PortfolioFundStockId 생성
  - [x] private_portfolios_fund_bonds 테이블과 통신할 PortfolioFundBond Entity 생성
    - [x] PortfolioFundBond Entity의 복합키를 위한 PortfolioFundBondId 생성 
- [x] ResponseDto 생성
  - [x] 자체 서비스 포트폴리오 내 펀드 상세 응답을 위한 ResponseDto 생성
