### ISSUE TITLE
♻️자체 서비스 내 포트폴리오 조회 로직 수정

### ISSUE THREAD

**Issue by SEO-YJ** [hit-it-PDA/BE#40]
## 📌 Description
- 자체 서비스 내 포트폴리오 조회 로직 수정

## 📝 To-do
- [x] 가져온 private_portfolios_fund_products 데이터를 정렬
  - [x] weight 순으로 내림차순
  - [x] weight가 같으면 fund_name으로 알파벳, 한글 순서
