### ISSUE TITLE
✨ 포트폴리오 전체 기능 구현 (자산 - 포트폴리오, Spring -Flask 통신, 포트폴리오 추천, 리밸런싱, 포트폴리오 선택)

### ISSUE THREAD

**Issue by SEO-YJ** [hit-it-PDA/BE#46]
## 📌 Description
- 자산 서비스에서 내 포트폴리오 비중 보기
- 자산 서비스에서 내 포트폴리오 내 펀드 보기
- 자산 서비스에서 내 포트폴리오 내 펀드 내 주식, 채권 보기
- 개별 EC2 내에서 Spring - Flask 통신
- 마이데이터 기반 포트폴리오 추천
- 포트폴리오 리밸런싱
- 자체 서비스 포트폴리오 상품 선택하기, 선택 후 변경하기

## 📝 To-do
- 자산 서비스에서 내 포트폴리오 비중 보기
  - [x] Controller
    - [x] 사용자에게 POST로 user_id를 전달하기 위해 PortfolioController 수정

  - [x] Service
    - [x] UserPortfolioFundRequestDto를 UserPortfolio Entity로 변경
    - [x] users_portfolio 테이블에서 전달받은 user_id를 id로 portfolio_id 조회
    - [x] portfolio_id로 private_portfolio 테이블에서 해당하는 포트폴리오 조회
    - [x] private_portfolio의 id로 포트폴리오 내 모든 펀드 조회
    - [x] 펀드 리스트를 반복하면서 각 펀드의 fund_code로 private_portfolio_fund_assets를 각각 가져와 국내 주식, 해외 주식, 국내 채권, 해외 채권, 수익 증권, 기타의 값을 모두 더한 후 펀드 리스트의 크기로 나누어 내 포트폴리오의 국내 주식, 해외 주식, 국내 채권, 해외 채권, 수익 증권, 기타의 값의 비율을 구함 

  - [x] Entity
    - [x] users_porfolio 테이블에서 User 조회를 위한 Entity 개발

  - [x] Dto 
    - [x] 사용자 아이디를 전달 받기 위한 UserPortfolioFundRequestDto 생성
    - [x] 내 포트폴리오 비중을 반환하기 위한 PortfolioFundAssetResponseDto 생성

  - [x] Repository
    - [x] 사용자 아이디를 users_portfolio 테이블에서 조회하기 위한 repository 생성
 
  - [x] 포트폴리오 내 주식, 채권 비율 로직 변경
    - 기존: ex> My Portfolio stock: (totalStock) / fundlist 갯수
    - 수정: ex> My Portfolio stock: (stock1 * (weight/100)) + (stock2 * (weight/100))

- [x] 개별 EC2 내에서 Spring - Flask 통신
  - [x] OpenFeign
    - [x] Flask와 통신을 테스트할 FlaskTestServiceClient 구현
    - [x] 마이데이터를 통해 포트폴리오를 전달 받을 MyDataPortfolioServiceClient 구현
    - [x] env.properties에 OpenFeign으로 통신할 url 설정
  - [x] Controller
    - [x]  Flask와 통신을 테스트할 PortfolioController 수정
    - [x] 마이데이터를 포트폴리오를 전달 받을 PortfolioController 수정
  - [x] Service
    - [x]  Flask와 통신을 테스트할 PortfolioService 수정
    - [x] 마이데이터를 포트폴리오를 전달 받을 PortfolioService 수정
    
  ----- Refactoring -----
- 자산 서비스에서 내 포트폴리오 비중 보기
  - [x] Entity
    - [x] UserPortfolios - user_portfolios 테이블 Entity
  - [x] Repository
    - [x]   UserPortfoliosRepository - user_portfolios 테이블 Repository
 
- 자산 서비스에서 내 포트폴리오 내 펀드 보기
- [x] Entity
    - [x] UserPortfoliosFundProducts - user_portfolios_fund_products 테이블 Entity
  - [x] Repository
    - [x]   UserPortfoliosFundProductsRepository - user_portfolios_fund_products 테이블 Repository

- 자산 서비스에서 내 포트폴리오 내 펀드 내 주식, 채권 보기
- [x] Entity
    - [x] FundProducts - fund_products_4 테이블 Entity
    - [x] FundStocks - fund_stocks 테이블 Entity
    - [x] FundBonds - fund_bonds 테이블 Entity
  - [x] Repository
    - [x]   FundProducts Repository - fund_products_4 테이블 Repository
     - [x]   FundStocksRepository - fund_stocks 테이블 Repository
      - [x]   FundBondsRepository - fund_bonds 테이블 Repository

- 마이데이터 기반 포트폴리오 추천
- [x] OpenFeign
  - [x] MyDataPortfolioServiceClient: ML 서버에 마이데이터 기반 포트폴리오 요청
- [x] Dto
  - [x] MyDataFundData: 마이데이터 넣고 ML 서버에 요청
  - [x] MyDataFlaskResponseDto: 마이데이터 넣고 ML 서버에 요청에 대한 응답
  - [x] MyDataFlaskLevelTest: userId, level 넣고 ML 서버에 요청
  - [x] MyDataFlaskLevelTestResponseDtd: userId, level 넣고 ML 서버에 요청에 대한 응답 

- 포트폴리오 리밸런싱
- [x] Dto
  - [x] FundProductDto: fundCode, weight 저장
  - [x] OptimizeDto: userId와 FundProductDto를 저장
  - [x] OptimizeResponseDto: 리밸런싱 응답을 저장
- [x] OpenFeign
  - [x]  OptimizeServiceClient: ML 서버에 리밸런싱 요청

- 자체 서비스 포트폴리오 상품 선택하기, 선택 후 변경하기
- [x] Controller
  - [x] PortfolioController에  해당 기능 추가
- [x] Service
  - [x] PortfolioService에 해당 기능 추가
- [x] Repository
  - [x]  UserPortfoliosRepository: userId로 포트폴리오 데이터 지우는 메서드 선언
  - [x] UserPortfoliosFundProductsRepository: portfolioId로 펀드 데이터 지우는 메서드 선언
