### ISSUE TITLE
♻️ MSA 구조 변경 

### ISSUE THREAD

**Issue by youhyeoneee** [hit-it-PDA/BE#60]
## 📌 Description
- 

## 📝 To-do
- [x] build.gradle 수정
- [x] security 패키지 이동
- [ ] asset-service user 엔티티 삭제
- [ ] asset-service, portfolio-service 테이블 제약 조건 삭제 및 user 테이블 삭제
- [x] #69
- [ ] 인증 필요한 곳 / 불필요한 곳 정리

**Comment by youhyeoneee** [comment]
추후 리팩토링 시 참고 자료 
https://velog.io/@jyleedev/AuthenticationPrincipal-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EC%A0%95%EB%B3%B4-%EB%B0%9B%EC%95%84%EC%98%A4%EA%B8%B0
